# -*- coding: utf-8 -*-
"""
建筑配置 - 配置层

设计思路:
    定义所有建筑设置的配置格式，实现配置驱动架构。
    统一配置格式，便于管理和扩展。

功能:
    1. 定义建筑配置格式
    2. 提供建筑配置数据
    3. 支持配置扩展

数据来源:
    静态配置数据。

使用场景:
    被 ConfigManager 调用。
"""

# *** 用户指定变量 - AI不得修改 ***
DEFAULT_DROPDOWN_WIDTH = 60  # 下拉框默认宽度
# *********************************

# 等级选项 (01-20)
LEVELS = [f"{i:02d}" for i in range(1, 21)]
LEVELS_0 = [f"{i:02d}" for i in range(0, 21)]

# 建筑配置字典
建筑配置 = {
    "主帅主城": {
        "card_type": "standard",
        "title": "主帅主城",
        "icon": "HOME",
        "subtitle": "",
        "enabled": True,
        "controls_per_row": 6,
        "controls": [
            {
                "type": "dropdown",
                "config_key": "主帅主城_城市",
                "label": "城市",
                "options": LEVELS,
                "value": "17",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_兵工",
                "label": "兵工",
                "options": LEVELS,
                "value": "17",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_陆军",
                "label": "陆军",
                "options": LEVELS,
                "value": "14",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_空军",
                "label": "空军",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_商业",
                "label": "商业",
                "options": LEVELS,
                "value": "04",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_补给",
                "label": "补给",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_内塔",
                "label": "内塔",
                "options": LEVELS,
                "value": "04",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_村庄",
                "label": "村庄",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_资源",
                "label": "资源",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_军工",
                "label": "军工",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_港口",
                "label": "港口",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅主城_外塔",
                "label": "外塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
        ],
    },
    "主帅分城": {
        "card_type": "standard",
        "title": "主帅分城",
        "icon": "LOCATION_CITY",
        "subtitle": "",
        "enabled": True,
        "controls_per_row": 6,
        "controls": [
            {
                "type": "dropdown",
                "config_key": "主帅分城_城市",
                "label": "城市",
                "options": LEVELS,
                "value": "15",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_兵工",
                "label": "兵工",
                "options": LEVELS,
                "value": "10",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_陆军",
                "label": "陆军",
                "options": LEVELS,
                "value": "10",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_空军",
                "label": "空军",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_商业",
                "label": "商业",
                "options": LEVELS,
                "value": "04",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_补给",
                "label": "补给",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_内塔",
                "label": "内塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_村庄",
                "label": "村庄",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_资源",
                "label": "资源",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_军工",
                "label": "军工",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_港口",
                "label": "港口",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "主帅分城_外塔",
                "label": "外塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
        ],
    },
    "付帅主城": {
        "card_type": "standard",
        "title": "付帅主城",
        "icon": "APARTMENT",
        "subtitle": "",
        "enabled": True,
        "controls_per_row": 6,
        "controls": [
            {
                "type": "dropdown",
                "config_key": "付帅主城_城市",
                "label": "城市",
                "options": LEVELS,
                "value": "15",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_兵工",
                "label": "兵工",
                "options": LEVELS,
                "value": "10",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_陆军",
                "label": "陆军",
                "options": LEVELS,
                "value": "10",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_空军",
                "label": "空军",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_商业",
                "label": "商业",
                "options": LEVELS,
                "value": "04",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_补给",
                "label": "补给",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_内塔",
                "label": "内塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_村庄",
                "label": "村庄",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_资源",
                "label": "资源",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_军工",
                "label": "军工",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_港口",
                "label": "港口",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅主城_外塔",
                "label": "外塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
        ],
    },
    "付帅分城": {
        "card_type": "standard",
        "title": "付帅分城",
        "icon": "BUSINESS",
        "subtitle": "",
        "enabled": True,
        "controls_per_row": 6,
        "controls": [
            {
                "type": "dropdown",
                "config_key": "付帅分城_城市",
                "label": "城市",
                "options": LEVELS,
                "value": "15",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_兵工",
                "label": "兵工",
                "options": LEVELS,
                "value": "10",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_陆军",
                "label": "陆军",
                "options": LEVELS,
                "value": "10",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_空军",
                "label": "空军",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_商业",
                "label": "商业",
                "options": LEVELS,
                "value": "04",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_补给",
                "label": "补给",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_内塔",
                "label": "内塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_村庄",
                "label": "村庄",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_资源",
                "label": "资源",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_军工",
                "label": "军工",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_港口",
                "label": "港口",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "付帅分城_外塔",
                "label": "外塔",
                "options": LEVELS,
                "value": "03",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
        ],
    },
    "军团城市": {
        "card_type": "standard",
        "title": "军团城市",
        "icon": "FORT",
        "subtitle": "",
        "enabled": True,
        "controls_per_row": 4,
        "controls": [
            {
                "type": "dropdown",
                "config_key": "军团城市_城市",
                "label": "城市",
                "options": LEVELS,
                "value": "05",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "军团城市_兵工",
                "label": "兵工",
                "options": LEVELS,
                "value": "05",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "军团城市_军需",
                "label": "军需",
                "options": LEVELS,
                "value": "05",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "军团城市_编号",
                "label": "编号",
                "options": LEVELS,
                "value": "01",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "军团城市_陆军",
                "label": "陆军",
                "options": LEVELS_0,
                "value": "00",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "军团城市_空军",
                "label": "空军",
                "options": LEVELS_0,
                "value": "00",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
            {
                "type": "dropdown",
                "config_key": "军团城市_炮塔",
                "label": "炮塔",
                "options": LEVELS_0,
                "value": "00",
                "width": DEFAULT_DROPDOWN_WIDTH,
            },
        ],
    },
}
